stages:
- build
- test
- build-review
- review
- quality-security
- cleanup
- release
- deploy

variables:
  URL: "budata.dbogatov.org" # if you include 'website-deploy'
  INDEX: "index.html"
  DIST: "dist"
  REPO: "bu/data-lab/website"
  AUTHPASSWORD: ""

include:
  # BEFORE SCRIPT
  - project: 'templates/ci-snippets'
    file: 'simple-website/before-script.yml'

  # TEST
  - project: 'templates/ci-snippets'
    file: 'simple-website/tidy.yml'

  - project: 'templates/ci-snippets'
    file: 'simple-website/blc.yml'

  # BUILD-REVIEW
  - project: 'templates/ci-snippets'
    file: 'simple-website/review/build-review.yml'

  # REVIEW
  - project: 'templates/ci-snippets'
    file: 'simple-website/review/review.yml'

  - project: 'templates/ci-snippets'
    file: 'simple-website/review/stop-review.yml'

  # RELEASE
  - project: 'templates/ci-snippets'
    file: 'simple-website/release-docker.yml'

  # DEPLOY
  - project: 'templates/ci-snippets'
    file: 'trigger-websites-deploy.yml'

build:
  image: dbogatov/docker-images:python-extras-latest
  stage: build
  script:
  - pip3 install -r requirements.txt
  - ./scripts/build.py
  artifacts:
    expire_in: 30 min
    paths:
    - dist
  tags:
  - docker
