stages:
  - pre-build
  - build
  - build-review
  - review
  - test
  - release
  - deploy

variables:
  DIST: "dist"
  REPO: "bu/data-lab/website"
  AUTHPASSWORD: ""
  DOCKER_TLS_CERTDIR: ""

  CI_REF: &ref 9452801422f44f0ec61ebe2179a6a7473ffd6d3d

include:
  # BEFORE SCRIPT
  - project: "templates/ci-snippets"
    file: "simple-website/before-script.yml"
    ref: *ref

  # BUILD-REVIEW
  - project: "templates/ci-snippets"
    file: "simple-website/review/build-review.yml"
    ref: *ref

  # REVIEW
  - project: "templates/ci-snippets"
    file: "simple-website/review/review.yml"
    ref: *ref

  - project: "templates/ci-snippets"
    file: "simple-website/review/stop-review.yml"
    ref: *ref

  # TEST
  - project: "templates/ci-snippets"
    file: "simple-website/blc.yml"
    ref: *ref

  # RELEASE
  - project: "templates/ci-snippets"
    file: "simple-website/release-docker.yml"
    ref: *ref

  - project: "templates/ci-snippets"
    file: "simple-website/pages.yml"
    ref: *ref

  # DEPLOY
  - project: "templates/ci-snippets"
    file: "trigger-websites-deploy.yml"
    ref: *ref

build:
  image: dbogatov/docker-images:python-extras-latest
  stage: build
  script:
    - pip3 install -r requirements.txt
    - ./scripts/build.py
  artifacts:
    expire_in: 30 min
    paths:
      - dist
  tags:
    - docker
