# Redirects will be generated in the form of "midas.bu.edu/classes/CODE" => URL

- code: CS460
  url: https://https://bu-disc.github.io/CS460/

- code: CS591A1
  url: https://midaslab-bu.github.io/CS591A1/
